<?php

namespace Ocpi\Modules\Locations\Enums;

use Eosvolt\Foundation\EnumArrayable;

enum EvseCapability: string
{
    use EnumArrayable;
    case CHARGING_PROFILE_CAPABLE = 'CHARGING_PROFILE_CAPABLE';
    case CHARGING_PREFERENCES_CAPABLE = 'CHARGING_PREFERENCES_CAPABLE';
    case CHIP_CARD_SUPPORT = 'CHIP_CARD_SUPPORT';
    case CONTACTLESS_CARD_SUPPORT = 'CONTACTLESS_CARD_SUPPORT';
    case CREDIT_CARD_PAYABLE = 'CREDIT_CARD_PAYABLE';
    case DEBIT_CARD_PAYABLE = 'DEBIT_CARD_PAYABLE';
    case PED_TERMINAL = 'PED_TERMINAL';
    case REMOTE_START_STOP_CAPABLE = 'REMOTE_START_STOP_CAPABLE';
    case RESERVABLE = 'RESERVABLE';
    case RFID_READER = 'RFID_READER';
    case START_SESSION_CONNECTOR_REQUIRED = 'START_SESSION_CONNECTOR_REQUIRED';
    case TOKEN_GROUP_CAPABLE = 'TOKEN_GROUP_CAPABLE';
    case UNLOCK_CAPABLE = 'UNLOCK_CAPABLE';
}
